<a href="https://colab.research.google.com/github/Aarush-coding/Pytorch_Journey/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
!nvidia-smi


Sun Jun  8 09:46:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
print( torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.6.0+cu124


##Introduction to Tensors

###Creating tensors

PyTorch tensors are created using 'torch.Tensor()' = https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get scalar back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors
why random tensors ?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers ...
```
Random Tensors documentation = https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [ ]:
# create random tensor of shape / size (2,3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.1962, 0.1587, 0.6939, 0.1224],
         [0.3026, 0.6611, 0.0641, 0.1538],
         [0.9101, 0.8666, 0.5963, 0.6951]],

        [[0.1542, 0.2167, 0.0156, 0.9868],
         [0.5563, 0.5430, 0.4773, 0.4144],
         [0.9746, 0.6930, 0.7750, 0.3702]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# create a random tensor with similar chape to an image tensor
image = torch.rand((224,224,3))# hight, width, colour channels(R G B)
image.shape, image.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros (3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype #float 32 is basic datatype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
onetoten = torch.arange(0,10, 2)#start, end ,step
onetoten

tensor([0, 2, 4, 6, 8])

In [ ]:
# ceating tensors like
tenzeros = torch.zeros_like(input=onetoten)# same shape as the tensor given in
tenzeros

tensor([0, 0, 0, 0, 0])

 ### Tensor Datatypes

 **Note!** Tensor datatypes is one of the three big erros you'll run into when using pytorch & deeplearning
 1. Tensors not right datatype
 2. Tensors not right shape
 3. Tensors not on the right device


In [ ]:
# float 32 tensor
float32tensor = torch.tensor([3.0,6.0,9.0],
                             dtype = None, # what is the datatype of the tensor - default is float32
                             device= None ,# Allow your to run on a Gpu (cuda) or the cpu
                             requires_grad = False) # tracking graients
float32tensor

tensor([3., 6., 9.])

In [ ]:
float32tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float32tensor.type(torch.half)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors (Tensor Attibutes)
1. Tensors not right datatype  - to get datatype from a type use tensor.dtype
2. Tensors not right shape - tensor.shape
3. Tensors not on the right device - tensor.device

In [ ]:
#Create Tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8879, 0.3410, 0.3323, 0.4471],
        [0.1103, 0.6700, 0.9975, 0.5267],
        [0.1379, 0.9628, 0.7625, 0.3067]])

In [ ]:
# Find Details
print(f'The datatype of this tensor is {some_tensor.dtype}:\nThe shape of the tensor is {some_tensor.shape}\nThe device it is running on is {some_tensor.device}')

The datatype of this tensor is torch.float32:
The shape of the tensor is torch.Size([3, 4])
The device it is running on is cpu


### Manipulating tensors (tensor operations)
Tensor operations include:
* Addition
* Subtraction
* multiplication(element wise)
* Division
* matrix multiplicaton

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor = tensor * 10

In [ ]:
tensor


tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([ 0, 10, 20])

In [ ]:
# try out pytorch inbuilt funciutons
torch.mul(tensor, 2)

tensor([20, 40, 60])

In [ ]:
torch.add(tensor, 10 )

tensor([20, 30, 40])

### Matrix Multilplication

Two main ways of performing multiplication in neural networks and deep learning

1. element wise
2. martix multiplication (dot product)

There are two main rules for matmul(you can use 'mm'):
1. The **inner** dimensions must match
2. the resulting matrix will have the dame dimensions as the **outer dimensions**:

In [ ]:
# element wise multiplication
print (f"{tensor} * {tensor}")
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [ ]:
# testing runtime comperd to by hand
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 988 µs, sys: 0 ns, total: 988 µs
Wall time: 942 µs


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 26 µs, sys: 4 µs, total: 30 µs
Wall time: 33.1 µs


tensor(1400)

### One of the most common  errors in deep learning: shape errors

**Shapes for matmul**

```
 A = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])

 B = torch.tensor([[7,10],
                  [8,11],
                  [9,12]])
 torch.mm(A,B)
```


flags an error as the tensor's inside dimensions don't match

To fix our tensor shape issue we can **Transpose** the shape of the tensor by switching the axis of dimensions
- rows become columns
- columns become rows


In [ ]:
A = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])

B = torch.tensor([[7,10],
                  [8,11],
                  [9,12]])

In [ ]:
B.T, B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
B, B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

## Finding the min, max,sum etc. (tensor aggrigation)

In [ ]:
# create a Tensor
x = torch.arange(0,100,10)
x, x.dtype #long dataptype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#find the minimum
x.min()

tensor(0)

In [ ]:
#find max
x.max()

tensor(90)

**This line gives an error**
```
x.mean()
```
This is because the mean doesnt allow long dtype as the input


In [ ]:
x.type(torch.float32).mean() # change the dtype

tensor(45.)

In [ ]:
# find the sum
x.sum()

tensor(450)

### Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# index of the minimum with agrmin()
x.argmin()

tensor(0)

In [ ]:
# index of the maximim with argmax()
x.argmax()

tensor(9)

### Reshaping , stacking , sqeezing and unsqueezing tensors
* Reshaping - Reshapes an input tensor of a defined shpae
* View - Return a view of an input tensor of a certain shape but keep the same memory
* Stacking - combining multiple tensors on top of each other (vstack) or (hstack)
* Sqeeze - Removes all, all '1' dimensions form a tensor
* Unsqueeze - add a '1' dimesion to target tensor
* Permute - Return a view of the input tesnors with the dimensions permuted (swapped) in a certain way


In [ ]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(3,3) # the number of items in the original tensor must be same as reshaped tensor
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
x_reshaped = x.reshape(9,1) # the number of items in the original tensor must be same as reshaped tensor
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (beacause the view of a tensor shares the smae memory as the origninal input )
z[:, 0] = 5
z,z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Stack
x_stacked = torch.stack([x, x, x , x], dim = 1 )# y axis
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x , x], dim = 0 )# x axis
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Squeezing
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape # removes all dimesions with value 1

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to taget tensor ata specific dimension
print(f"Orginal: {x_squeezed}")
print(f"Orginal shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed  = x_squeezed.unsqueeze(dim = 1)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Orginal: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Orginal shape: torch.Size([9])
New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])
