<a href="https://colab.research.google.com/github/Aarush-coding/Pytorch_Journey/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
!git clone https://github.com/Aarush-coding/Pytorch_Journey.git
%cd Pytorch_Journey

Cloning into 'Pytorch_Journey'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 2), reused 2 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (11/11), 12.67 KiB | 67.00 KiB/s, done.
Resolving deltas: 100% (2/2), done.
/content/Pytorch_Journey


## 00. Pytorch fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [85]:
!nvidia-smi


Wed Jul  2 16:39:08 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P0             30W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
print( torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.6.0+cu124


##Introduction to Tensors

###Creating tensors

PyTorch tensors are created using 'torch.Tensor()' = https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get scalar back as python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim


2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors
why random tensors ?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers ...
```
Random Tensors documentation = https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [17]:
# create random tensor of shape / size (2,3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.3994, 0.9211, 0.5938, 0.9177],
         [0.1369, 0.3195, 0.3425, 0.1116],
         [0.4840, 0.8292, 0.6499, 0.2921]],

        [[0.2625, 0.4256, 0.7394, 0.3911],
         [0.2550, 0.6037, 0.1362, 0.5849],
         [0.8177, 0.5740, 0.1168, 0.4551]]])

In [18]:
random_tensor.ndim

3

In [19]:
# create a random tensor with similar chape to an image tensor
image = torch.rand((224,224,3))# hight, width, colour channels(R G B)
image.shape, image.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [20]:
# create a tensor of all zeros
zeros = torch.zeros (3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype #float 32 is basic datatype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
onetoten = torch.arange(0,10, 2)#start, end ,step
onetoten

tensor([0, 2, 4, 6, 8])

In [25]:
# ceating tensors like
tenzeros = torch.zeros_like(input=onetoten)# same shape as the tensor given in
tenzeros

tensor([0, 0, 0, 0, 0])

 ### Tensor Datatypes

 **Note!** Tensor datatypes is one of the three big erros you'll run into when using pytorch & deeplearning
 1. Tensors not right datatype
 2. Tensors not right shape
 3. Tensors not on the right device


In [26]:
# float 32 tensor
float32tensor = torch.tensor([3.0,6.0,9.0],
                             dtype = None, # what is the datatype of the tensor - default is float32
                             device= None ,# Allow your to run on a Gpu (cuda) or the cpu
                             requires_grad = False) # tracking graients
float32tensor

tensor([3., 6., 9.])

In [27]:
float32tensor.dtype

torch.float32

In [28]:
float_16_tensor = float32tensor.type(torch.half)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors (Tensor Attibutes)
1. Tensors not right datatype  - to get datatype from a type use tensor.dtype
2. Tensors not right shape - tensor.shape
3. Tensors not on the right device - tensor.device

In [30]:
#Create Tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2909, 0.4077, 0.3848, 0.0575],
        [0.4410, 0.6351, 0.7665, 0.6997],
        [0.6834, 0.7014, 0.9816, 0.1498]])

In [31]:
# Find Details
print(f'The datatype of this tensor is {some_tensor.dtype}:\nThe shape of the tensor is {some_tensor.shape}\nThe device it is running on is {some_tensor.device}')

The datatype of this tensor is torch.float32:
The shape of the tensor is torch.Size([3, 4])
The device it is running on is cpu


### Manipulating tensors (tensor operations)
Tensor operations include:
* Addition
* Subtraction
* multiplication(element wise)
* Division
* matrix multiplicaton

In [32]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor

tensor([1, 2, 3])

In [34]:
tensor = tensor * 10

In [35]:
tensor


tensor([10, 20, 30])

In [36]:
tensor - 10

tensor([ 0, 10, 20])

In [37]:
# try out pytorch inbuilt funciutons
torch.mul(tensor, 2)

tensor([20, 40, 60])

In [38]:
torch.add(tensor, 10 )

tensor([20, 30, 40])

### Matrix Multilplication

Two main ways of performing multiplication in neural networks and deep learning

1. element wise
2. martix multiplication (dot product)

There are two main rules for matmul(you can use 'mm'):
1. The **inner** dimensions must match
2. the resulting matrix will have the dame dimensions as the **outer dimensions**:

In [39]:
# element wise multiplication
print (f"{tensor} * {tensor}")
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [41]:
# testing runtime comperd to by hand
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 817 µs, sys: 0 ns, total: 817 µs
Wall time: 5.5 ms


In [42]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 40 µs, sys: 7 µs, total: 47 µs
Wall time: 49.4 µs


tensor(1400)

### One of the most common  errors in deep learning: shape errors

**Shapes for matmul**

```
 A = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])

 B = torch.tensor([[7,10],
                  [8,11],
                  [9,12]])
 torch.mm(A,B)
```


flags an error as the tensor's inside dimensions don't match

To fix our tensor shape issue we can **Transpose** the shape of the tensor by switching the axis of dimensions
- rows become columns
- columns become rows


In [43]:
A = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])

B = torch.tensor([[7,10],
                  [8,11],
                  [9,12]])

In [44]:
B.T, B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [45]:
B, B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

## Finding the min, max,sum etc. (tensor aggrigation)

In [46]:
# create a Tensor
x = torch.arange(0,100,10)
x, x.dtype #long dataptype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [47]:
#find the minimum
x.min()

tensor(0)

In [48]:
#find max
x.max()

tensor(90)

**This line gives an error**
```
x.mean()
```
This is because the mean doesnt allow long dtype as the input


In [49]:
x.type(torch.float32).mean() # change the dtype

tensor(45.)

In [50]:
# find the sum
x.sum()

tensor(450)

### Finding the positional min and max

In [51]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
# index of the minimum with agrmin()
x.argmin()

tensor(0)

In [53]:
# index of the maximim with argmax()
x.argmax()

tensor(9)

### Reshaping , stacking , sqeezing and unsqueezing tensors
* Reshaping - Reshapes an input tensor of a defined shpae
* View - Return a view of an input tensor of a certain shape but keep the same memory
* Stacking - combining multiple tensors on top of each other (vstack) or (hstack)
* Sqeeze - Removes all, all '1' dimensions form a tensor
* Unsqueeze - add a '1' dimesion to target tensor
* Permute - Return a view of the input tesnors with the dimensions permuted (swapped) in a certain way


In [54]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
# Add an extra dimension
x_reshaped = x.reshape(3,3) # the number of items in the original tensor must be same as reshaped tensor
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [56]:
x_reshaped = x.reshape(9,1) # the number of items in the original tensor must be same as reshaped tensor
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [57]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
# Changing z changes x (beacause the view of a tensor shares the smae memory as the origninal input )
z[:, 0] = 5
z,z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
# Stack
x_stacked = torch.stack([x, x, x , x], dim = 1 )# y axis
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [60]:
x_stacked = torch.stack([x, x, x , x], dim = 0 )# x axis
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [61]:
# Squeezing
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [62]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
x_reshaped.squeeze().shape # removes all dimesions with value 1

torch.Size([9])

In [64]:
# torch.unsqueeze() - adds a single dimension to taget tensor ata specific dimension
print(f"Orginal: {x_squeezed}")
print(f"Orginal shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed  = x_squeezed.unsqueeze(dim = 1)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Orginal: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Orginal shape: torch.Size([9])
New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [65]:
# Torch.permute - rearranges the dimensions of a target tensor
x_orig = torch.rand(size = (224,224,3))# height , width , color channels
print(f"Original Shape is: {x_orig.shape}")

# permute x to rearrange the axis order
permuted = x_orig.permute(2,0,1) # shifts axis 0->1 1->2 2->1
print(f"Permuted shape is: {permuted.shape}")

Original Shape is: torch.Size([224, 224, 3])
Permuted shape is: torch.Size([3, 224, 224])


### Indexing (seleceting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy


In [66]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [67]:
# indexing
x[0] # 0th dimension index

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
x[0,0]

tensor([1, 2, 3])

In [69]:
# indexing on the most inner bracket (last dimension)
x[0,0,0] # 0th index on the 0th line on the 0th dimension

tensor(1)

In [70]:
x[0,2,2]

tensor(9)

In [71]:
  # you can also use ':' to select all of target dim
  x[:,0]

tensor([[1, 2, 3]])

In [72]:
# get last row
x[:,:,2]

tensor([[3, 6, 9]])

# Pytorch tensors & numpy

Numpy is a popular scientific Python numerical computing library
Pytorch has functionality to interact with it

* Data in Numpy , want in Pytorch Tensor -> torch.from_numpy (ndarray)
* Pytorch tensor -> numpy -> torch.tensor.numpy()






In [73]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch .from_numpy(array) # warning when converting from numpy to pytorch, pytorch reflects numpy's default datatype (float 64)
array ,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Chage value of array , impact on 'tensor' ?
array = array + 1
array , tensor # tensor doesnt change

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [75]:
# Tensor to numpy array
tensor = (torch.ones(7))
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [76]:
# change the tensor, impact on numpy tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducability ( trying to the take the random out of random )

To reduce the randomness we use
**random seed**.

random seed "flavours" the randomness

In [77]:
import torch
# random tensors
A = torch.rand(3,4)
B = torch.rand(3,4)
print(A)
print(B)
print(A == B)

tensor([[0.9754, 0.3641, 0.7307, 0.9154],
        [0.1973, 0.5748, 0.6935, 0.2087],
        [0.9720, 0.8291, 0.2243, 0.6861]])
tensor([[0.8431, 0.6857, 0.0886, 0.0013],
        [0.4354, 0.8576, 0.5762, 0.3196],
        [0.1185, 0.4093, 0.7714, 0.5623]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [78]:
# random but reproducable tensors
import torch
# set random seed
RANDSEED = 42

torch.manual_seed(RANDSEED)
random_tensor = torch.rand(3,4)

torch.manual_seed(RANDSEED)
random_tensor2 = torch.rand(3,4) # randomness of the same flavour of 42

print(random_tensor)
print(random_tensor2)
print(random_tensor == random_tensor2)# if run by someone else the randomness is the same

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and Pytorch objects on GPUs (making faster computation)

GPUs = faster number computation thanks to CUDA + NVIDIA hardware + Pytorch BTS

from sre_constants import GROUPREF_UNI_IGNORE
### 1. Getting a GPU
1. Easiest = Use Google Colab free GPU
2. Use your own GPU
3. Use cloud computing - GCP AWS, Azure - rent computers on cloud platforms and access them

In [79]:
## seting up the gpu using cuda
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

## Putting Tensors and models on the GPU

In [80]:
# create a tensor on the CPU
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [81]:
# move to tensor to GPU runtime if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor.device


(tensor([1, 2, 3], device='cuda:0'), device(type='cpu'))

In [82]:
# numpy manipulaiton can only occur on the cpu
# to change the device back to the CPU
Tensor_oncpu = tensor_on_gpu.cpu().numpy()
Tensor_oncpu, Tensor_oncpu.device # changes back to the cpu from cuda

(array([1, 2, 3]), 'cpu')

In [83]:
!nvidia-smi

Wed Jul  2 16:39:06 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P0             30W /   70W |     104MiB /  15360MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Exercises & extracurriculum

In [99]:
import torch
randtensor1 = torch.rand([7,7])
randtensor1

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [101]:
randtensor2 = torch.rand([1,7])
randtensor2

tensor([[0.0600, 0.2846, 0.2007, 0.5014, 0.3139, 0.4654, 0.1612]])

In [102]:
torch.mm(randtensor1, randtensor2.T)

tensor([[0.6796]])